# -*- coding: utf-8 -*-
"""DiaCare_flask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13n83nPFkIHgZnM_Wzg3oXdnjmT_Ra7AW
"""

import numpy as np
import cv2
from flask import Flask, request, jsonify
from tensorflow.keras.models import load_model
from flask_cors import CORS
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Input
# Initialisation Flask
app = Flask(__name__)

# Activation CORS pour Angular / Spring Boot
CORS(app)
IMG_SIZE = 150
model = Sequential([
    Input(shape=(IMG_SIZE, IMG_SIZE, 3)),
    Conv2D(32, (3,3), activation='relu'),
    MaxPooling2D(2,2),
    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),
    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

#  Charger les poids
model.load_weights("DiaCare1.h5")



# Fonction de prétraitement
def preprocess_image(image):
    image = cv2.resize(image, (IMG_SIZE, IMG_SIZE))
    image = image / 255.0
    image = np.reshape(image, (1, IMG_SIZE, IMG_SIZE, 3))
    return image


# Route de prédiction
@app.route('/predict', methods=['POST'])
def predict():

    if 'file' not in request.files:
        return jsonify({"error": "No file uploaded"}), 400

    file = request.files['file']

    # Convertir fichier en image
    file_bytes = np.frombuffer(file.read(), np.uint8)
    img = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)

    if img is None:
        return jsonify({"error": "Invalid image"}), 400

    # Prétraitement
    processed_img = preprocess_image(img)

    # Prédiction
    prediction = model.predict(processed_img)[0][0]

    if prediction > 0.5:
        result = "Diabetes"
        confidence = float(prediction)
    else:
        result = "NonDiabetes"
        confidence = float(1 - prediction)

    return jsonify({
        "prediction": result,
        "confidence": round(confidence * 100, 2)
    })


# Lancement du serveur
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5002, debug=True)