# -*- coding: utf-8 -*-
"""femme-diacare.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Buzix0QQVuTLERyIqO5i0kwwoksxE59
"""

import os, json, logging, numpy as np, pandas as pd, joblib
from datetime import datetime
from functools import wraps
from flask import Flask, request, jsonify
from flask_cors import CORS

# ============================================================
# CONFIGURATION
# ============================================================

app = Flask(__name__)

CORS(app)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger(__name__)

# ============================================================
# CHEMINS — CORRIGÉS : utilise os.getcwd() au lieu de __file__
# ============================================================
# os.getcwd() = dossier depuis lequel tu lances `python app.py`
# Place tes fichiers .pkl dans un sous-dossier "models/" à côté de app.py

BASE_DIR   = os.getcwd()
MODELS_DIR = os.path.join(BASE_DIR, "models")

MODEL_PATH  = os.path.join(MODELS_DIR, "diacare_model.pkl")
SCALER_PATH = os.path.join(MODELS_DIR, "diacare_scaler.pkl")
META_PATH   = os.path.join(MODELS_DIR, "diacare_metadata.json")

# ============================================================
# CHARGEMENT DU MODÈLE
# ============================================================

def load_model():
    try:
        model  = joblib.load(MODEL_PATH)
        scaler = joblib.load(SCALER_PATH)
        with open(META_PATH, "r", encoding="utf-8") as f:
            metadata = json.load(f)
        logger.info(f"✓ Modèle chargé — AUC: {metadata['metrics']['roc_auc']}")
        return model, scaler, metadata
    except FileNotFoundError as e:
        logger.error(f"✗ Fichier introuvable : {e}")
        logger.error(f"  Vérifie que tes .pkl sont dans : {MODELS_DIR}")
        raise

MODEL, SCALER, METADATA = load_model()
THRESHOLD     = METADATA.get("threshold", 0.40)
FEATURE_NAMES = METADATA.get("features", [])

# Valeurs max du dataset Pima — nécessaires pour Risk_score
GLUCOSE_MAX = 199.0
BMI_MAX     = 67.1
AGE_MAX     = 81.0

# ============================================================
# UTILITAIRES
# ============================================================

def build_features(data: dict) -> pd.DataFrame:
    """Reconstruit les 13 features à partir des 8 variables brutes."""
    preg = float(data["Pregnancies"])
    gluc = float(data["Glucose"])
    bp   = float(data["BloodPressure"])
    skin = float(data["SkinThickness"])
    ins  = float(data["Insulin"])
    bmi  = float(data["BMI"])
    dpf  = float(data["DiabetesPedigreeFunction"])
    age  = float(data["Age"])

    row = {
        "Pregnancies"            : preg,
        "Glucose"                : gluc,
        "BloodPressure"          : bp,
        "SkinThickness"          : skin,
        "Insulin"                : ins,
        "BMI"                    : bmi,
        "DiabetesPedigreeFunction": dpf,
        "Age"                    : age,
        # Feature engineering — identique au notebook
        "BMI_Age"                : bmi * age,
        "Glucose_sq"             : gluc ** 2,
        "Insulin_Glucose"        : ins / (gluc + 1),
        "Age_cat"                : 0 if age < 30 else (1 if age <= 45 else 2),
        "Risk_score"             : (gluc/GLUCOSE_MAX + bmi/BMI_MAX + age/AGE_MAX) / 3,
    }
    return pd.DataFrame([row])[FEATURE_NAMES]


def validate_input(data: dict) -> list:
    """Valide les 8 champs requis et leurs plages médicales."""
    errors = []
    fields = {
        "Pregnancies"            : (0,   20,   "Grossesses"),
        "Glucose"                : (44,  200,  "Glucose (mg/dL)"),
        "BloodPressure"          : (24,  122,  "Pression artérielle (mm Hg)"),
        "SkinThickness"          : (0,   110,  "Épaisseur cutanée (mm)"),
        "Insulin"                : (0,   850,  "Insuline (µU/mL)"),
        "BMI"                    : (10,  70,   "IMC"),
        "DiabetesPedigreeFunction": (0.0, 2.5, "Indice familial"),
        "Age"                    : (18,  90,   "Âge"),
    }
    for field, (lo, hi, label) in fields.items():
        if field not in data:
            errors.append(f"Champ manquant : {field}")
            continue
        try:
            val = float(data[field])
            if not (lo <= val <= hi):
                errors.append(f"{label} hors plage : {val} (attendu {lo}–{hi})")
        except (ValueError, TypeError):
            errors.append(f"{field} doit être un nombre")
    return errors


def interpret_result(proba: float, pred: int) -> dict:
    pct = round(proba * 100, 1)
    if pred == 0:
        level, color = ("très faible", "green") if proba < 0.20 else ("modéré", "yellow")
        msg = "Les paramètres n'indiquent pas de risque de diabète." if proba < 0.20 \
              else "Paramètres dans la normale — surveillance conseillée."
    else:
        level, color = ("modéré-élevé", "orange") if proba < 0.65 else ("élevé", "red")
        msg = "Certains indicateurs suggèrent un risque. Consultez un médecin." if proba < 0.65 \
              else "Indicateurs fortement associés au diabète. Consultation recommandée."

    return {
        "prediction"      : int(pred),
        "label"           : "Diabétique" if pred == 1 else "Non-diabétique",
        "probability"     : round(proba, 4),
        "probability_pct" : pct,
        "risk_level"      : level,
        "color"           : color,
        "message"         : msg,
        "threshold_used"  : THRESHOLD,
        "disclaimer"      : "Résultat indicatif. Ne remplace pas un avis médical.",
    }


def require_json(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if not request.is_json:
            return jsonify({"error": "Content-Type doit être application/json"}), 415
        return f(*args, **kwargs)
    return wrapper

# ============================================================
# ROUTES
# ============================================================

@app.route("/", methods=["GET"])
def index():
    return jsonify({
        "service": "DiaCare Prediction API",
        "version": METADATA.get("version", "1.0.0"),
        "status" : "running",
        "routes" : ["/health", "/api/info", "/api/predict", "/api/predict/batch"],
    })


@app.route("/health", methods=["GET"])
def health():
    return jsonify({
        "status"   : "ok",
        "model"    : "loaded",
        "threshold": THRESHOLD,
        "timestamp": datetime.utcnow().isoformat() + "Z",
    })


@app.route("/api/info", methods=["GET"])
def model_info():
    return jsonify({
        "model_name"   : METADATA.get("model_name"),
        "version"      : METADATA.get("version"),
        "threshold"    : THRESHOLD,
        "features"     : FEATURE_NAMES,
        "feature_count": len(FEATURE_NAMES),
        "metrics"      : METADATA.get("metrics", {}),
        "input_fields" : [
            {"name": "Pregnancies",              "type": "int",   "min": 0,   "max": 20,  "unit": ""},
            {"name": "Glucose",                  "type": "float", "min": 44,  "max": 200, "unit": "mg/dL"},
            {"name": "BloodPressure",            "type": "float", "min": 24,  "max": 122, "unit": "mm Hg"},
            {"name": "SkinThickness",            "type": "float", "min": 0,   "max": 110, "unit": "mm"},
            {"name": "Insulin",                  "type": "float", "min": 0,   "max": 850, "unit": "µU/mL"},
            {"name": "BMI",                      "type": "float", "min": 10,  "max": 70,  "unit": "kg/m²"},
            {"name": "DiabetesPedigreeFunction", "type": "float", "min": 0.0, "max": 2.5, "unit": ""},
            {"name": "Age",                      "type": "int",   "min": 18,  "max": 90,  "unit": "années"},
        ],
    })


@app.route("/api/predict", methods=["POST"])
@require_json
def predict():
    """
    Prédiction pour un seul patient.

    Exemple de corps JSON :
    {
        "Pregnancies": 3, "Glucose": 120, "BloodPressure": 70,
        "SkinThickness": 25, "Insulin": 80, "BMI": 28.5,
        "DiabetesPedigreeFunction": 0.45, "Age": 35
    }
    """
    data   = request.get_json()
    errors = validate_input(data)
    if errors:
        return jsonify({"success": False, "errors": errors}), 400

    try:
        X_df    = build_features(data)
        X_sc    = SCALER.transform(X_df)
        proba   = MODEL.predict_proba(X_sc)[0][1]
        pred    = int(proba >= THRESHOLD)
        result  = interpret_result(proba, pred)

        logger.info(f"Predict → {result['label']} ({proba:.3f}) | {request.remote_addr}")

        return jsonify({
            "success"      : True,
            "result"       : result,
            "features_used": X_df.iloc[0].round(4).to_dict(),
            "timestamp"    : datetime.utcnow().isoformat() + "Z",
        })

    except Exception as e:
        logger.exception("Erreur prédiction")
        return jsonify({"success": False, "error": "Erreur interne"}), 500


@app.route("/api/predict/batch", methods=["POST"])
@require_json
def predict_batch():
    """Prédiction pour plusieurs patients (max 50)."""
    data = request.get_json()
    if "patients" not in data or not isinstance(data["patients"], list):
        return jsonify({"success": False, "error": "Clé 'patients' requise (liste)"}), 400
    if len(data["patients"]) > 50:
        return jsonify({"success": False, "error": "Maximum 50 patients par requête"}), 400

    results = []
    for i, patient in enumerate(data["patients"]):
        errors = validate_input(patient)
        if errors:
            results.append({"index": i, "success": False, "errors": errors})
            continue
        try:
            X_df  = build_features(patient)
            X_sc  = SCALER.transform(X_df)
            proba = MODEL.predict_proba(X_sc)[0][1]
            pred  = int(proba >= THRESHOLD)
            results.append({"index": i, "success": True, "result": interpret_result(proba, pred)})
        except Exception as e:
            results.append({"index": i, "success": False, "error": str(e)})

    ok = sum(1 for r in results if r.get("success"))
    return jsonify({
        "success"      : True,
        "total"        : len(data["patients"]),
        "success_count": ok,
        "results"      : results,
        "timestamp"    : datetime.utcnow().isoformat() + "Z",
    })


# ============================================================
# GESTION DES ERREURS
# ============================================================

@app.errorhandler(404)
def not_found(e):
    return jsonify({"error": "Route introuvable", "status": 404}), 404

@app.errorhandler(405)
def method_not_allowed(e):
    return jsonify({"error": "Méthode non autorisée", "status": 405}), 405

@app.errorhandler(500)
def internal_error(e):
    return jsonify({"error": "Erreur interne", "status": 500}), 500


# ============================================================
# LANCEMENT
# ============================================================

if __name__ == "__main__":
    port  = int(os.environ.get("PORT", 5000))
    debug = os.environ.get("FLASK_DEBUG", "false").lower() == "true"
    logger.info(f"DiaCare API → http://localhost:{port}")
    app.run(host="0.0.0.0", port=port, debug=debug)