# -*- coding: utf-8 -*-
"""predit_diabete.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fmSwgkJowM8r7vEEDMyAbB4-IQUAwS28
"""

# predit_diabete.py
from flask import Flask, request, jsonify
from flask_cors import CORS
import joblib
import numpy as np

# Initialisation
app = Flask(__name__)
CORS(app)

# Charger modèle + scaler
model = joblib.load('diabetes_model.pkl')
scaler = joblib.load('scaler.pkl')

# Route test
@app.route('/')
def home():
    return "API Diabetes is running"

# Route prediction
@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = request.json
        print("📥 Données reçues:", data)

        # Ordre exact des features
        features = [
            data['Age'],
            data['Gender'],
            data['Polyuria'],
            data['Polydipsia'],
            data['sudden_weight_loss'],
            data['weakness'],
            data['Polyphagia'],
            data['Genital_thrush'],
            data['visual_blurring'],
            data['Itching'],
            data['Irritability'],
            data['delayed_healing'],
            data['partial_paresis'],
            data['muscle_stiffness'],
            data['Alopecia'],
            data['Obesity']
        ]

        features = np.array(features).reshape(1, -1)
        print("📊 Features:", features)

        # Scaling
        features = scaler.transform(features)
        print("📈 Features scaled:", features)

        # Prediction
        prediction = model.predict(features)[0]

        # ✅ AJOUTER LA PROBABILITÉ
        probability = model.predict_proba(features)[0][1]

        print("🎯 Prediction:", prediction)
        print("📊 Probability:", probability)

        result = "Diabète détecté" if prediction == 1 else "Non diabétique"
        risk_level = "Élevé" if prediction == 1 else "Faible"

        return jsonify({
            'prediction': int(prediction),
            'result': result,
            'probability': float(probability),
            'riskLevel': risk_level,
            'recommendations': get_recommendations(prediction, data)
        })

    except Exception as e:
        print("❌ Erreur:", str(e))
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 400

def get_recommendations(prediction, data):
    recommendations = []

    if prediction == 1:
        recommendations.append("Consultez un médecin endocrinologue rapidement")
        recommendations.append("Surveillez votre glycémie régulièrement")
        recommendations.append("Adoptez une alimentation équilibrée pauvre en sucre")
        recommendations.append("Pratiquez une activité physique régulière")
    else:
        recommendations.append("Maintenez une alimentation saine et équilibrée")
        recommendations.append("Faites vérifier votre glycémie une fois par an")
        recommendations.append("Pratiquez une activité physique régulière")

    if data.get('Obesity', 0) == 1:
        recommendations.append("Perdez du poids progressivement (objectif: 5-10% de votre poids)")

    return recommendations

# Run serveur
if __name__ == '__main__':
    app.run(debug=True, port=5007, host='0.0.0.0')