spring.application.name=diaCare-backend

# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/diacare_db?&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# SERVER
server.port=8081


# Dossier d'upload
file.upload-dir=C:/Users/21622/Desktop/diaCare-backend/uploads


# MULTIPART
spring.servlet.multipart.enabled=true
# Limite de fichier individuel
spring.servlet.multipart.max-file-size=10MB
# Limite totale de la requête
spring.servlet.multipart.max-request-size=10MB
# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jihandhaoui65@gmail.com
spring.mail.password=eckaqvdwwmpmgdkh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Thymeleaf
#spring.thymeleaf.check-template-location=false
stripe.api.key=${STRIPE_SECRET_KEY}
stripe.publishable.key=pk_test_51TESqOPdOkHJhkaV0VzqbW3jOMKNMhkctJhM3mwhuhDzMMg6G3AMs7BxxREzNK7pGjhtdkpy8vuGkTlafoyWHexU00IWPM8chC

