spring.application.name=diaCare-backend
spring.datasource.url=jdbc:mysql://localhost:3306/diacare_db?&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8081
spoonacular.token=d84acf965bd1440da0e6374facd0ab2f
